---
title: "Hourly Shaped Montecarlo Simulation"
author: "Alejandro Abraham"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Hourly Shaped Montecarlo Simulation}
  %\VignetteEngine{knitr::rmarkdown}
---

## Setup

```{r, setup}

box::use(
  data.table[...],
  magrittr[...],
  echarts4r[...],
  reactable[...],
  HPFC[...],
  openxlsx[...]
)

## sim path
sim_path = 'mc_run'

## Spot curve
dt_spot_pwr = fread(file.path(sim_path, 'history', 'history_pwr.csv'))
dt_spot_pwr = dt_spot_pwr[date >= '2023-01-01']

## fwd curve
dt_fwd_pwr = fread(file.path(sim_path, 'fwds', 'base_fwd_curve.csv'))
dt_fwd_gas = fread(file.path(sim_path, 'fwds', 'base_fwd_curve_gas.csv'))

## Load models
ENV_MODELS_GAS = readRDS(file.path(sim_path, 'models', 'ENV_MODELS_GAS.rds'))
ENV_MODELS_PWR = readRDS(file.path(sim_path, 'models', 'ENV_MODELS_PWR.rds'))

```

### Preview Spot data
```{r, spot table}
## Spot curve
reactable(dt_spot_pwr)
```


```{r, sim}
sim_result = montecarlo_sim(
  S0 = 100,
  Td = 365,
  N = 20,
  dt_spot_pwr = dt_spot_pwr,
  dt_fwd_pwr = dt_fwd_pwr
)
```

### Sim results
```{r, sim table}
reactable(sim_result)
```


```{r, sim plot}
sim_result |>
  group_by(sim) |>
  e_charts(yymm) |>
  e_line(value) |>
  e_title("Monte Carlo Simulation of a Random Walk") |>
  e_x_axis(name = "Time (Months)") |>
  e_y_axis(name = "Price") |>
  e_tooltip(trigger = "axis") |> 
  e_toolbox_feature(feature = "saveAsImage", title = "Save as image") %>% 
  e_datazoom(start = 0)  |>
  e_legend(orient = "vertical", right = 0) |>
  e_theme("westeros")  
```

## Hourly Shaping
```{r, setup fwds}
dt_fwd_prep_pwr = merge(dt_fwd_pwr, generate_monthrics_pwr('Romania', time_range = 2024), by.x = 'yymm', by.y ='date', all.x = TRUE) 
dt_fwd_prep_gas = merge(dt_fwd_gas, generate_monthrics_gas('TFMB', time_range = 2024), by.x = 'yymm', by.y ='date', all.x = TRUE) 
dt_fwds = rbind(dt_fwd_prep_pwr, dt_fwd_prep_gas)
dt_fwds[, sim := NULL]
colnames(dt_fwds) = c('date', 'value', 'RIC')

list_inputs_fwd = prepare_fwd(
    fwd_pwr_code = 'Greece',
    fwd_gas_code = 'TTF',
    start_date = min(dt_fwd_pwr$yymm, na.rm = TRUE),
    end_date = max(dt_fwd_pwr$yymm, na.rm = TRUE),
    model_type = 'PWR',
    forecast_source = 'FWD',
    archive = 'NO',
    manual_pwr = dt_fwd_pwr,
    manual_gas = dt_fwd_gas
)



```

### Preview FWDs
```{r, table fwds}
reactable(dt_fwds)
```

```{r, montecarlo apply function}
apply_shape = function(
                       country = 'Italy',
                       name = 'HPFC',
                       start_date = '2024-01-01', 
                       end_date = '2024-12-31',
                       dt_fwd_pwr,
                       dt_spot_pwr,
                       dt_fwd_gas,
                       dt_spot_gas,
                       model_gas = ENV_MODELS_GAS,
                       model_pwr = ENV_MODELS_PWR
                       ) {
    
    spot_pwr_code = unique(dt_spot_pwr$RIC)
    spot_gas_code = 'TTFDA'
    fwd_pwr_code = unique(HPFC::spot_PWR_products_full[countries == country]$products_PWR_code)
    fwd_gas_code = 'TFMB'
    
    last_date = as.Date(start_date) - 1
    calendar_holidays = as.data.table(HPFC::new_calendar_holidays)
    setnames(calendar_holidays, paste0("holiday_", country), 'holiday', skip_absent = TRUE)
    calendar_future = calendar_holidays[, .(date, holiday)]
    calendar_future[,`:=` (year = as.character(data.table::year(date)), 
                           quarter = as.character(data.table::quarter(date)),
                           month = as.character(data.table::month(date)))
    ]
    calendar_future = calendar_future[date >= start_date & date <= end_date]
    time_range = as.numeric(data.table::year(as.Date(start_date))):as.numeric(data.table::year(as.Date(end_date)))
    
    dt_fwd_prep_pwr = merge(dt_fwd_pwr, generate_monthrics_pwr(country, time_range = 2024), by.x = 'yymm', by.y ='date', all.x = TRUE) 
    dt_fwd_prep_gas = merge(dt_fwd_gas, generate_monthrics_gas(fwd_gas_code, time_range = 2024), by.x = 'yymm', by.y ='date', all.x = TRUE) 
    
    dt_fwds = rbind(dt_fwd_prep_pwr, dt_fwd_prep_gas)
    dt_fwds[, sim := NULL]
    colnames(dt_fwds) = c('date', 'value', 'RIC')
    
    LST_FOR = list(
        model_lt_gas = copy(model_gas$dt_lt_param_gasdep),
        model_lt_pwr = copy(model_pwr$dt_lt_param_pwr),
        model_st_pwr = copy(model_pwr$lst_hr_param_pwr),
        dt_fwds = copy(dt_fwds),
        saved_history_gas = dt_spot_gas,
        saved_history_pwr = dt_spot_pwr,
        ric_spot_gas = spot_gas_code,
        ric_fwd_gas = fwd_gas_code,
        ric_spot_pwr = spot_pwr_code,
        ric_fwd_pwr = fwd_pwr_code,
        calendar_forecast = calendar_future,
        start_date = start_date,
        end_date = end_date,
        last_date = last_date
    ) 
    
    ENV_FOR_GAS = forecast_gas(input_forecast = LST_FOR)
    ENV_FOR_PWR = forecast_pwr(input_forecast = LST_FOR, gas_forecast = ENV_FOR_GAS)
    
    dt_pwr = ENV_FOR_PWR[, .(date, hour, forecast = final_forecast)]
    setcolorder(dt_pwr, c('date', 'hour',  'forecast'))
    setorder(dt_pwr, date, hour)
    dt_pwr[, name := name]
    
    return(dt_pwr)

}
```

```{r, fwd apply}
DT_FWD = apply_shape(
                    country = 'Greece',
                    name = 'FWD',
                    start_date = '2024-01-01',
                    end_date = '2024-12-31',
                    dt_fwd_pwr = dt_fwd_pwr,
                    dt_spot_pwr = dt_spot_pwr,
                    dt_fwd_gas = dt_fwd_gas,
                    dt_spot_gas = dt_spot_gas,
                    model_gas = ENV_MODELS_GAS,
                    model_pwr = ENV_MODELS_PWR
)
```


```{r, sim apply}
# Get the unique simulations from the sim_result
vec_sims = unique(sim_result$sim)

# Apply the function to each unique simulation
results = lapply(vec_sims, function(sim_id) {
  # Filter the data for the current simulation
  dt_fwd_pwr_filtered = sim_result[sim == sim_id]

  # Call the apply_shape function with the necessary parameters
  DTS = apply_shape(
                    country = 'Greece',
                    name = sim_id,
                    start_date = '2024-01-01',
                    end_date = '2024-12-31',
                    dt_fwd_pwr = dt_fwd_pwr_filtered,
                    dt_spot_pwr = dt_spot_pwr,
                    dt_fwd_gas = dt_fwd_gas,
                    dt_spot_gas = dt_spot_gas,
                    model_gas = ENV_MODELS_GAS,
                    model_pwr = ENV_MODELS_PWR
  )
  
  cat(crayon::cyan$bold(paste0("✔ Simulation ", sim_id, " completed\n")))
  
  # Return the result for this simulation
  return(DTS)
  
})

DT_HPFC_MC = rbindlist(results)
```

```{r, plot hpfc montecarlo}
DT_HPFC_MC[, .(value = mean(forecast, na.rm = TRUE)), by = .(yymm = date, sim = name)] |>
  group_by(sim) |>
  e_charts(yymm) |>
  e_line(value, symbol = 'none') |>
  e_title("HPFC - Monte Carlo Price paths") |>
  e_x_axis(name = "Time (Months)") |>
  e_y_axis(name = "Price") |>
  e_tooltip(trigger = "axis") |> 
  e_toolbox_feature(feature = "saveAsImage", title = "Save as image") %>% 
  e_datazoom(start = 0)  |>
  e_legend(orient = "vertical", right = 0) |>
  e_theme("westeros")  

```

```{r, export}
openxlsx::write.xlsx(DT_HPFC_MC, file = file.path(sim_path, 'output', 'hpfc_mc_curves.xlsx'))
```

