
#' Estimate the hourly seasonality model
#'
#' The function use a nls function ...
#'
#' @param x A hourly DT.
#' @param y Gas Price column name.
#' @returns A nls object representing the hourly model
#' @import data.table
#' @export

hourly_model = function(DT){

  DTW=copy(DT)

  DTW[, value_gas2 := value_gas^2]

  nls.control(maxiter = 50, tol = 1e-05, minFactor = 1/2100,
              printEval = FALSE, warnOnly = FALSE, scaleOffset = 0,
              nDcentral = FALSE)

  model_h=nls(value_h ~
                hour_1*coeff_hour_1+
                hour_2*coeff_hour_2+
                hour_3*coeff_hour_3+
                hour_4*coeff_hour_4+
                hour_5*coeff_hour_5+
                hour_6*coeff_hour_6+
                hour_7*coeff_hour_7+
                hour_8*coeff_hour_8+
                hour_9*coeff_hour_9+
                hour_10*coeff_hour_10+
                hour_11*coeff_hour_11+
                hour_12*coeff_hour_12+
                hour_13*coeff_hour_13+
                hour_14*coeff_hour_14+
                hour_15*coeff_hour_15+
                hour_16*coeff_hour_16+
                hour_17*coeff_hour_17+
                hour_18*coeff_hour_18+
                hour_19*coeff_hour_19+
                hour_20*coeff_hour_20+
                hour_21*coeff_hour_21+
                hour_22*coeff_hour_22+
                hour_23*coeff_hour_23+
                (-1*(coeff_hour_1+coeff_hour_2+
                       coeff_hour_3+coeff_hour_4+
                       coeff_hour_5+coeff_hour_6+
                       coeff_hour_7+coeff_hour_8+
                       coeff_hour_9+coeff_hour_10+
                       coeff_hour_11+coeff_hour_12+
                       coeff_hour_13+coeff_hour_14+
                       coeff_hour_15+coeff_hour_16+
                       coeff_hour_17+coeff_hour_18+
                       coeff_hour_19+coeff_hour_20+
                       coeff_hour_21+coeff_hour_22+
                       coeff_hour_23))*hour_24+ # end hour_ dummy --------------
              hour_1*bl*coeff_bl_hour_1+
                hour_2*bl*coeff_bl_hour_2+
                hour_3*bl*coeff_bl_hour_3+
                hour_4*bl*coeff_bl_hour_4+
                hour_5*bl*coeff_bl_hour_5+
                hour_6*bl*coeff_bl_hour_6+
                hour_7*bl*coeff_bl_hour_7+
                hour_8*bl*coeff_bl_hour_8+
                hour_9*bl*coeff_bl_hour_9+
                hour_10*bl*coeff_bl_hour_10+
                hour_11*bl*coeff_bl_hour_11+
                hour_12*bl*coeff_bl_hour_12+
                hour_13*bl*coeff_bl_hour_13+
                hour_14*bl*coeff_bl_hour_14+
                hour_15*bl*coeff_bl_hour_15+
                hour_16*bl*coeff_bl_hour_16+
                hour_17*bl*coeff_bl_hour_17+
                hour_18*bl*coeff_bl_hour_18+
                hour_19*bl*coeff_bl_hour_19+
                hour_20*bl*coeff_bl_hour_20+
                hour_21*bl*coeff_bl_hour_21+
                hour_22*bl*coeff_bl_hour_22+
                hour_23*bl*coeff_bl_hour_23+
                (-1*(coeff_bl_hour_1+coeff_bl_hour_2+
                       coeff_bl_hour_3+coeff_bl_hour_4+
                       coeff_bl_hour_5+coeff_bl_hour_6+
                       coeff_bl_hour_7+coeff_bl_hour_8+
                       coeff_bl_hour_9+coeff_bl_hour_10+
                       coeff_bl_hour_11+coeff_bl_hour_12+
                       coeff_bl_hour_13+coeff_bl_hour_14+
                       coeff_bl_hour_15+coeff_bl_hour_16+
                       coeff_bl_hour_17+coeff_bl_hour_18+
                       coeff_bl_hour_19+coeff_bl_hour_20+
                       coeff_bl_hour_21+coeff_bl_hour_22+
                       coeff_bl_hour_23))*hour_24*bl + # end hour_ bl interaction --------------
              hour_1*bl2*coeff_bl2_hour_1+
                hour_2*bl2*coeff_bl2_hour_2+
                hour_3*bl2*coeff_bl2_hour_3+
                hour_4*bl2*coeff_bl2_hour_4+
                hour_5*bl2*coeff_bl2_hour_5+
                hour_6*bl2*coeff_bl2_hour_6+
                hour_7*bl2*coeff_bl2_hour_7+
                hour_8*bl2*coeff_bl2_hour_8+
                hour_9*bl2*coeff_bl2_hour_9+
                hour_10*bl2*coeff_bl2_hour_10+
                hour_11*bl2*coeff_bl2_hour_11+
                hour_12*bl2*coeff_bl2_hour_12+
                hour_13*bl2*coeff_bl2_hour_13+
                hour_14*bl2*coeff_bl2_hour_14+
                hour_15*bl2*coeff_bl2_hour_15+
                hour_16*bl2*coeff_bl2_hour_16+
                hour_17*bl2*coeff_bl2_hour_17+
                hour_18*bl2*coeff_bl2_hour_18+
                hour_19*bl2*coeff_bl2_hour_19+
                hour_20*bl2*coeff_bl2_hour_20+
                hour_21*bl2*coeff_bl2_hour_21+
                hour_22*bl2*coeff_bl2_hour_22+
                hour_23*bl2*coeff_bl2_hour_23+
                (-1*(coeff_bl2_hour_1+coeff_bl2_hour_2+
                       coeff_bl2_hour_3+coeff_bl2_hour_4+
                       coeff_bl2_hour_5+coeff_bl2_hour_6+
                       coeff_bl2_hour_7+coeff_bl2_hour_8+
                       coeff_bl2_hour_9+coeff_bl2_hour_10+
                       coeff_bl2_hour_11+coeff_bl2_hour_12+
                       coeff_bl2_hour_13+coeff_bl2_hour_14+
                       coeff_bl2_hour_15+coeff_bl2_hour_16+
                       coeff_bl2_hour_17+coeff_bl2_hour_18+
                       coeff_bl2_hour_19+coeff_bl2_hour_20+
                       coeff_bl2_hour_21+coeff_bl2_hour_22+
                       coeff_bl2_hour_23))*hour_24*bl2 + # end hour_ bl2 interaction --------------
              hour_1*bl3*coeff_bl3_hour_1+
                hour_2*bl3*coeff_bl3_hour_2+
                hour_3*bl3*coeff_bl3_hour_3+
                hour_4*bl3*coeff_bl3_hour_4+
                hour_5*bl3*coeff_bl3_hour_5+
                hour_6*bl3*coeff_bl3_hour_6+
                hour_7*bl3*coeff_bl3_hour_7+
                hour_8*bl3*coeff_bl3_hour_8+
                hour_9*bl3*coeff_bl3_hour_9+
                hour_10*bl3*coeff_bl3_hour_10+
                hour_11*bl3*coeff_bl3_hour_11+
                hour_12*bl3*coeff_bl3_hour_12+
                hour_13*bl3*coeff_bl3_hour_13+
                hour_14*bl3*coeff_bl3_hour_14+
                hour_15*bl3*coeff_bl3_hour_15+
                hour_16*bl3*coeff_bl3_hour_16+
                hour_17*bl3*coeff_bl3_hour_17+
                hour_18*bl3*coeff_bl3_hour_18+
                hour_19*bl3*coeff_bl3_hour_19+
                hour_20*bl3*coeff_bl3_hour_20+
                hour_21*bl3*coeff_bl3_hour_21+
                hour_22*bl3*coeff_bl3_hour_22+
                hour_23*bl3*coeff_bl3_hour_23+
                (-1*(coeff_bl3_hour_1+coeff_bl3_hour_2+
                       coeff_bl3_hour_3+coeff_bl3_hour_4+
                       coeff_bl3_hour_5+coeff_bl3_hour_6+
                       coeff_bl3_hour_7+coeff_bl3_hour_8+
                       coeff_bl3_hour_9+coeff_bl3_hour_10+
                       coeff_bl3_hour_11+coeff_bl3_hour_12+
                       coeff_bl3_hour_13+coeff_bl3_hour_14+
                       coeff_bl3_hour_15+coeff_bl3_hour_16+
                       coeff_bl3_hour_17+coeff_bl3_hour_18+
                       coeff_bl3_hour_19+coeff_bl3_hour_20+
                       coeff_bl3_hour_21+coeff_bl3_hour_22+
                       coeff_bl3_hour_23))*hour_24*bl3 + # end hour_ bl3 interaction --------------
                  # NEW SEASONAL REGRESSORS
              season_winter*coeff_season_winter +
                     season_spring*coeff_season_spring +
                     season_summer*coeff_season_summer +
                     season_fall*coeff_season_fall +         
              hour_1*yday*coeff_yday_hour_1+
                hour_2*yday*coeff_yday_hour_2+
                hour_3*yday*coeff_yday_hour_3+
                hour_4*yday*coeff_yday_hour_4+
                hour_5*yday*coeff_yday_hour_5+
                hour_6*yday*coeff_yday_hour_6+
                hour_7*yday*coeff_yday_hour_7+
                hour_8*yday*coeff_yday_hour_8+
                hour_9*yday*coeff_yday_hour_9+
                hour_10*yday*coeff_yday_hour_10+
                hour_11*yday*coeff_yday_hour_11+
                hour_12*yday*coeff_yday_hour_12+
                hour_13*yday*coeff_yday_hour_13+
                hour_14*yday*coeff_yday_hour_14+
                hour_15*yday*coeff_yday_hour_15+
                hour_16*yday*coeff_yday_hour_16+
                hour_17*yday*coeff_yday_hour_17+
                hour_18*yday*coeff_yday_hour_18+
                hour_19*yday*coeff_yday_hour_19+
                hour_20*yday*coeff_yday_hour_20+
                hour_21*yday*coeff_yday_hour_21+
                hour_22*yday*coeff_yday_hour_22+
                hour_23*yday*coeff_yday_hour_23+
                (-1*(coeff_yday_hour_1+coeff_yday_hour_2+
                       coeff_yday_hour_3+coeff_yday_hour_4+
                       coeff_yday_hour_5+coeff_yday_hour_6+
                       coeff_yday_hour_7+coeff_yday_hour_8+
                       coeff_yday_hour_9+coeff_yday_hour_10+
                       coeff_yday_hour_11+coeff_yday_hour_12+
                       coeff_yday_hour_13+coeff_yday_hour_14+
                       coeff_yday_hour_15+coeff_yday_hour_16+
                       coeff_yday_hour_17+coeff_yday_hour_18+
                       coeff_yday_hour_19+coeff_yday_hour_20+
                       coeff_yday_hour_21+coeff_yday_hour_22+
                       coeff_yday_hour_23))*hour_24*yday + # end hour_ yday interaction --------------
              hour_1*yday2*coeff_yday2_hour_1+
                hour_2*yday2*coeff_yday2_hour_2+
                hour_3*yday2*coeff_yday2_hour_3+
                hour_4*yday2*coeff_yday2_hour_4+
                hour_5*yday2*coeff_yday2_hour_5+
                hour_6*yday2*coeff_yday2_hour_6+
                hour_7*yday2*coeff_yday2_hour_7+
                hour_8*yday2*coeff_yday2_hour_8+
                hour_9*yday2*coeff_yday2_hour_9+
                hour_10*yday2*coeff_yday2_hour_10+
                hour_11*yday2*coeff_yday2_hour_11+
                hour_12*yday2*coeff_yday2_hour_12+
                hour_13*yday2*coeff_yday2_hour_13+
                hour_14*yday2*coeff_yday2_hour_14+
                hour_15*yday2*coeff_yday2_hour_15+
                hour_16*yday2*coeff_yday2_hour_16+
                hour_17*yday2*coeff_yday2_hour_17+
                hour_18*yday2*coeff_yday2_hour_18+
                hour_19*yday2*coeff_yday2_hour_19+
                hour_20*yday2*coeff_yday2_hour_20+
                hour_21*yday2*coeff_yday2_hour_21+
                hour_22*yday2*coeff_yday2_hour_22+
                hour_23*yday2*coeff_yday2_hour_23+
                (-1*(coeff_yday2_hour_1+coeff_yday2_hour_2+
                       coeff_yday2_hour_3+coeff_yday2_hour_4+
                       coeff_yday2_hour_5+coeff_yday2_hour_6+
                       coeff_yday2_hour_7+coeff_yday2_hour_8+
                       coeff_yday2_hour_9+coeff_yday2_hour_10+
                       coeff_yday2_hour_11+coeff_yday2_hour_12+
                       coeff_yday2_hour_13+coeff_yday2_hour_14+
                       coeff_yday2_hour_15+coeff_yday2_hour_16+
                       coeff_yday2_hour_17+coeff_yday2_hour_18+
                       coeff_yday2_hour_19+coeff_yday2_hour_20+
                       coeff_yday2_hour_21+coeff_yday2_hour_22+
                       coeff_yday2_hour_23))*hour_24*yday2 + # end hour_ yday2 interaction --------------
              hour_1*yday3*coeff_yday3_hour_1+
                hour_2*yday3*coeff_yday3_hour_2+
                hour_3*yday3*coeff_yday3_hour_3+
                hour_4*yday3*coeff_yday3_hour_4+
                hour_5*yday3*coeff_yday3_hour_5+
                hour_6*yday3*coeff_yday3_hour_6+
                hour_7*yday3*coeff_yday3_hour_7+
                hour_8*yday3*coeff_yday3_hour_8+
                hour_9*yday3*coeff_yday3_hour_9+
                hour_10*yday3*coeff_yday3_hour_10+
                hour_11*yday3*coeff_yday3_hour_11+
                hour_12*yday3*coeff_yday3_hour_12+
                hour_13*yday3*coeff_yday3_hour_13+
                hour_14*yday3*coeff_yday3_hour_14+
                hour_15*yday3*coeff_yday3_hour_15+
                hour_16*yday3*coeff_yday3_hour_16+
                hour_17*yday3*coeff_yday3_hour_17+
                hour_18*yday3*coeff_yday3_hour_18+
                hour_19*yday3*coeff_yday3_hour_19+
                hour_20*yday3*coeff_yday3_hour_20+
                hour_21*yday3*coeff_yday3_hour_21+
                hour_22*yday3*coeff_yday3_hour_22+
                hour_23*yday3*coeff_yday3_hour_23+
                (-1*(coeff_yday3_hour_1+coeff_yday3_hour_2+
                       coeff_yday3_hour_3+coeff_yday3_hour_4+
                       coeff_yday3_hour_5+coeff_yday3_hour_6+
                       coeff_yday3_hour_7+coeff_yday3_hour_8+
                       coeff_yday3_hour_9+coeff_yday3_hour_10+
                       coeff_yday3_hour_11+coeff_yday3_hour_12+
                       coeff_yday3_hour_13+coeff_yday3_hour_14+
                       coeff_yday3_hour_15+coeff_yday3_hour_16+
                       coeff_yday3_hour_17+coeff_yday3_hour_18+
                       coeff_yday3_hour_19+coeff_yday3_hour_20+
                       coeff_yday3_hour_21+coeff_yday3_hour_22+
                       coeff_yday3_hour_23))*hour_24*yday3 + # end hour_ yday3 interaction --------------
              hour_1*value_gas*coeff_value_gas_hour_1+
                hour_2*value_gas*coeff_value_gas_hour_2+
                hour_3*value_gas*coeff_value_gas_hour_3+
                hour_4*value_gas*coeff_value_gas_hour_4+
                hour_5*value_gas*coeff_value_gas_hour_5+
                hour_6*value_gas*coeff_value_gas_hour_6+
                hour_7*value_gas*coeff_value_gas_hour_7+
                hour_8*value_gas*coeff_value_gas_hour_8+
                hour_9*value_gas*coeff_value_gas_hour_9+
                hour_10*value_gas*coeff_value_gas_hour_10+
                hour_11*value_gas*coeff_value_gas_hour_11+
                hour_12*value_gas*coeff_value_gas_hour_12+
                hour_13*value_gas*coeff_value_gas_hour_13+
                hour_14*value_gas*coeff_value_gas_hour_14+
                hour_15*value_gas*coeff_value_gas_hour_15+
                hour_16*value_gas*coeff_value_gas_hour_16+
                hour_17*value_gas*coeff_value_gas_hour_17+
                hour_18*value_gas*coeff_value_gas_hour_18+
                hour_19*value_gas*coeff_value_gas_hour_19+
                hour_20*value_gas*coeff_value_gas_hour_20+
                hour_21*value_gas*coeff_value_gas_hour_21+
                hour_22*value_gas*coeff_value_gas_hour_22+
                hour_23*value_gas*coeff_value_gas_hour_23+
                (-1*(coeff_value_gas_hour_1+coeff_value_gas_hour_2+
                       coeff_value_gas_hour_3+coeff_value_gas_hour_4+
                       coeff_value_gas_hour_5+coeff_value_gas_hour_6+
                       coeff_value_gas_hour_7+coeff_value_gas_hour_8+
                       coeff_value_gas_hour_9+coeff_value_gas_hour_10+
                       coeff_value_gas_hour_11+coeff_value_gas_hour_12+
                       coeff_value_gas_hour_13+coeff_value_gas_hour_14+
                       coeff_value_gas_hour_15+coeff_value_gas_hour_16+
                       coeff_value_gas_hour_17+coeff_value_gas_hour_18+
                       coeff_value_gas_hour_19+coeff_value_gas_hour_20+
                       coeff_value_gas_hour_21+coeff_value_gas_hour_22+
                       coeff_value_gas_hour_23))*hour_24*value_gas + # end hour_ value_gas interaction --------------
              hour_1*value_gas2*coeff_value_gas2_hour_1+
                hour_2*value_gas2*coeff_value_gas2_hour_2+
                hour_3*value_gas2*coeff_value_gas2_hour_3+
                hour_4*value_gas2*coeff_value_gas2_hour_4+
                hour_5*value_gas2*coeff_value_gas2_hour_5+
                hour_6*value_gas2*coeff_value_gas2_hour_6+
                hour_7*value_gas2*coeff_value_gas2_hour_7+
                hour_8*value_gas2*coeff_value_gas2_hour_8+
                hour_9*value_gas2*coeff_value_gas2_hour_9+
                hour_10*value_gas2*coeff_value_gas2_hour_10+
                hour_11*value_gas2*coeff_value_gas2_hour_11+
                hour_12*value_gas2*coeff_value_gas2_hour_12+
                hour_13*value_gas2*coeff_value_gas2_hour_13+
                hour_14*value_gas2*coeff_value_gas2_hour_14+
                hour_15*value_gas2*coeff_value_gas2_hour_15+
                hour_16*value_gas2*coeff_value_gas2_hour_16+
                hour_17*value_gas2*coeff_value_gas2_hour_17+
                hour_18*value_gas2*coeff_value_gas2_hour_18+
                hour_19*value_gas2*coeff_value_gas2_hour_19+
                hour_20*value_gas2*coeff_value_gas2_hour_20+
                hour_21*value_gas2*coeff_value_gas2_hour_21+
                hour_22*value_gas2*coeff_value_gas2_hour_22+
                hour_23*value_gas2*coeff_value_gas2_hour_23+
                (-1*(coeff_value_gas2_hour_1+coeff_value_gas2_hour_2+
                       coeff_value_gas2_hour_3+coeff_value_gas2_hour_4+
                       coeff_value_gas2_hour_5+coeff_value_gas2_hour_6+
                       coeff_value_gas2_hour_7+coeff_value_gas2_hour_8+
                       coeff_value_gas2_hour_9+coeff_value_gas2_hour_10+
                       coeff_value_gas2_hour_11+coeff_value_gas2_hour_12+
                       coeff_value_gas2_hour_13+coeff_value_gas2_hour_14+
                       coeff_value_gas2_hour_15+coeff_value_gas2_hour_16+
                       coeff_value_gas2_hour_17+coeff_value_gas2_hour_18+
                       coeff_value_gas2_hour_19+coeff_value_gas2_hour_20+
                       coeff_value_gas2_hour_21+coeff_value_gas2_hour_22+
                       coeff_value_gas2_hour_23))*hour_24*value_gas2 + # end hour_ value_gas2 interaction --------------
              hour_1*weekend*coeff_weekend_hour_1+
                hour_2*weekend*coeff_weekend_hour_2+
                hour_3*weekend*coeff_weekend_hour_3+
                hour_4*weekend*coeff_weekend_hour_4+
                hour_5*weekend*coeff_weekend_hour_5+
                hour_6*weekend*coeff_weekend_hour_6+
                hour_7*weekend*coeff_weekend_hour_7+
                hour_8*weekend*coeff_weekend_hour_8+
                hour_9*weekend*coeff_weekend_hour_9+
                hour_10*weekend*coeff_weekend_hour_10+
                hour_11*weekend*coeff_weekend_hour_11+
                hour_12*weekend*coeff_weekend_hour_12+
                hour_13*weekend*coeff_weekend_hour_13+
                hour_14*weekend*coeff_weekend_hour_14+
                hour_15*weekend*coeff_weekend_hour_15+
                hour_16*weekend*coeff_weekend_hour_16+
                hour_17*weekend*coeff_weekend_hour_17+
                hour_18*weekend*coeff_weekend_hour_18+
                hour_19*weekend*coeff_weekend_hour_19+
                hour_20*weekend*coeff_weekend_hour_20+
                hour_21*weekend*coeff_weekend_hour_21+
                hour_22*weekend*coeff_weekend_hour_22+
                hour_23*weekend*coeff_weekend_hour_23+
                (-1*(coeff_weekend_hour_1+coeff_weekend_hour_2+
                       coeff_weekend_hour_3+coeff_weekend_hour_4+
                       coeff_weekend_hour_5+coeff_weekend_hour_6+
                       coeff_weekend_hour_7+coeff_weekend_hour_8+
                       coeff_weekend_hour_9+coeff_weekend_hour_10+
                       coeff_weekend_hour_11+coeff_weekend_hour_12+
                       coeff_weekend_hour_13+coeff_weekend_hour_14+
                       coeff_weekend_hour_15+coeff_weekend_hour_16+
                       coeff_weekend_hour_17+coeff_weekend_hour_18+
                       coeff_weekend_hour_19+coeff_weekend_hour_20+
                       coeff_weekend_hour_21+coeff_weekend_hour_22+
                       coeff_weekend_hour_23))*hour_24*weekend + # end hour_ weekend interaction --------------
              hour_1*break_h*coeff_break_h_hour_1+
                hour_2*break_h*coeff_break_h_hour_2+
                hour_3*break_h*coeff_break_h_hour_3+
                hour_4*break_h*coeff_break_h_hour_4+
                hour_5*break_h*coeff_break_h_hour_5+
                hour_6*break_h*coeff_break_h_hour_6+
                hour_7*break_h*coeff_break_h_hour_7+
                hour_8*break_h*coeff_break_h_hour_8+
                hour_9*break_h*coeff_break_h_hour_9+
                hour_10*break_h*coeff_break_h_hour_10+
                hour_11*break_h*coeff_break_h_hour_11+
                hour_12*break_h*coeff_break_h_hour_12+
                hour_13*break_h*coeff_break_h_hour_13+
                hour_14*break_h*coeff_break_h_hour_14+
                hour_15*break_h*coeff_break_h_hour_15+
                hour_16*break_h*coeff_break_h_hour_16+
                hour_17*break_h*coeff_break_h_hour_17+
                hour_18*break_h*coeff_break_h_hour_18+
                hour_19*break_h*coeff_break_h_hour_19+
                hour_20*break_h*coeff_break_h_hour_20+
                hour_21*break_h*coeff_break_h_hour_21+
                hour_22*break_h*coeff_break_h_hour_22+
                hour_23*break_h*coeff_break_h_hour_23+
                (-1*(coeff_break_h_hour_1+coeff_break_h_hour_2+
                       coeff_break_h_hour_3+coeff_break_h_hour_4+
                       coeff_break_h_hour_5+coeff_break_h_hour_6+
                       coeff_break_h_hour_7+coeff_break_h_hour_8+
                       coeff_break_h_hour_9+coeff_break_h_hour_10+
                       coeff_break_h_hour_11+coeff_break_h_hour_12+
                       coeff_break_h_hour_13+coeff_break_h_hour_14+
                       coeff_break_h_hour_15+coeff_break_h_hour_16+
                       coeff_break_h_hour_17+coeff_break_h_hour_18+
                       coeff_break_h_hour_19+coeff_break_h_hour_20+
                       coeff_break_h_hour_21+coeff_break_h_hour_22+
                       coeff_break_h_hour_23))*hour_24*break_h, # end hour_ break_group_h interaction --------------
              start=list(coeff_season_winter=0, coeff_season_spring=0, coeff_season_summer=0, coeff_season_fall=0, coeff_hour_1=0,coeff_hour_2=0,coeff_hour_3=0,coeff_hour_4=0,coeff_hour_5=0,coeff_hour_6=0,coeff_hour_7=0,coeff_hour_8=0,coeff_hour_9=0,coeff_hour_10=0,coeff_hour_11=0,coeff_hour_12=0,coeff_hour_13=0,
                         coeff_hour_14=0,coeff_hour_15=0,coeff_hour_16=0,coeff_hour_17=0,coeff_hour_18=0,coeff_hour_19=0,coeff_hour_20=0,coeff_hour_21=0,coeff_hour_22=0,coeff_hour_23=0,
                         coeff_bl_hour_1=0,coeff_bl_hour_2=0,coeff_bl_hour_3=0,coeff_bl_hour_4=0,coeff_bl_hour_5=0,coeff_bl_hour_6=0,coeff_bl_hour_7=0,coeff_bl_hour_8=0,coeff_bl_hour_9=0,coeff_bl_hour_10=0,coeff_bl_hour_11=0,coeff_bl_hour_12=0,coeff_bl_hour_13=0,
                         coeff_bl_hour_14=0,coeff_bl_hour_15=0,coeff_bl_hour_16=0,coeff_bl_hour_17=0,coeff_bl_hour_18=0,coeff_bl_hour_19=0,coeff_bl_hour_20=0,coeff_bl_hour_21=0,coeff_bl_hour_22=0,coeff_bl_hour_23=0,
                         coeff_bl2_hour_1=0,coeff_bl2_hour_2=0,coeff_bl2_hour_3=0,coeff_bl2_hour_4=0,coeff_bl2_hour_5=0,coeff_bl2_hour_6=0,coeff_bl2_hour_7=0,coeff_bl2_hour_8=0,coeff_bl2_hour_9=0,coeff_bl2_hour_10=0,coeff_bl2_hour_11=0,coeff_bl2_hour_12=0,coeff_bl2_hour_13=0,
                         coeff_bl2_hour_14=0,coeff_bl2_hour_15=0,coeff_bl2_hour_16=0,coeff_bl2_hour_17=0,coeff_bl2_hour_18=0,coeff_bl2_hour_19=0,coeff_bl2_hour_20=0,coeff_bl2_hour_21=0,coeff_bl2_hour_22=0,coeff_bl2_hour_23=0,
                         coeff_bl3_hour_1=0,coeff_bl3_hour_2=0,coeff_bl3_hour_3=0,coeff_bl3_hour_4=0,coeff_bl3_hour_5=0,coeff_bl3_hour_6=0,coeff_bl3_hour_7=0,coeff_bl3_hour_8=0,coeff_bl3_hour_9=0,coeff_bl3_hour_10=0,coeff_bl3_hour_11=0,coeff_bl3_hour_12=0,coeff_bl3_hour_13=0,
                         coeff_bl3_hour_14=0,coeff_bl3_hour_15=0,coeff_bl3_hour_16=0,coeff_bl3_hour_17=0,coeff_bl3_hour_18=0,coeff_bl3_hour_19=0,coeff_bl3_hour_20=0,coeff_bl3_hour_21=0,coeff_bl3_hour_22=0,coeff_bl3_hour_23=0,
                         coeff_yday_hour_1=0,coeff_yday_hour_2=0,coeff_yday_hour_3=0,coeff_yday_hour_4=0,coeff_yday_hour_5=0,coeff_yday_hour_6=0,coeff_yday_hour_7=0,coeff_yday_hour_8=0,coeff_yday_hour_9=0,coeff_yday_hour_10=0,coeff_yday_hour_11=0,coeff_yday_hour_12=0,coeff_yday_hour_13=0,
                         coeff_yday_hour_14=0,coeff_yday_hour_15=0,coeff_yday_hour_16=0,coeff_yday_hour_17=0,coeff_yday_hour_18=0,coeff_yday_hour_19=0,coeff_yday_hour_20=0,coeff_yday_hour_21=0,coeff_yday_hour_22=0,coeff_yday_hour_23=0,
                         coeff_yday2_hour_1=0,coeff_yday2_hour_2=0,coeff_yday2_hour_3=0,coeff_yday2_hour_4=0,coeff_yday2_hour_5=0,coeff_yday2_hour_6=0,coeff_yday2_hour_7=0,coeff_yday2_hour_8=0,coeff_yday2_hour_9=0,coeff_yday2_hour_10=0,coeff_yday2_hour_11=0,coeff_yday2_hour_12=0,coeff_yday2_hour_13=0,
                         coeff_yday2_hour_14=0,coeff_yday2_hour_15=0,coeff_yday2_hour_16=0,coeff_yday2_hour_17=0,coeff_yday2_hour_18=0,coeff_yday2_hour_19=0,coeff_yday2_hour_20=0,coeff_yday2_hour_21=0,coeff_yday2_hour_22=0,coeff_yday2_hour_23=0,
                         coeff_yday3_hour_1=0,coeff_yday3_hour_2=0,coeff_yday3_hour_3=0,coeff_yday3_hour_4=0,coeff_yday3_hour_5=0,coeff_yday3_hour_6=0,coeff_yday3_hour_7=0,coeff_yday3_hour_8=0,coeff_yday3_hour_9=0,coeff_yday3_hour_10=0,coeff_yday3_hour_11=0,coeff_yday3_hour_12=0,coeff_yday3_hour_13=0,
                         coeff_yday3_hour_14=0,coeff_yday3_hour_15=0,coeff_yday3_hour_16=0,coeff_yday3_hour_17=0,coeff_yday3_hour_18=0,coeff_yday3_hour_19=0,coeff_yday3_hour_20=0,coeff_yday3_hour_21=0,coeff_yday3_hour_22=0,coeff_yday3_hour_23=0,
                         coeff_value_gas_hour_1=0,coeff_value_gas_hour_2=0,coeff_value_gas_hour_3=0,coeff_value_gas_hour_4=0,coeff_value_gas_hour_5=0,coeff_value_gas_hour_6=0,coeff_value_gas_hour_7=0,coeff_value_gas_hour_8=0,coeff_value_gas_hour_9=0,coeff_value_gas_hour_10=0,coeff_value_gas_hour_11=0,coeff_value_gas_hour_12=0,coeff_value_gas_hour_13=0,
                         coeff_value_gas_hour_14=0,coeff_value_gas_hour_15=0,coeff_value_gas_hour_16=0,coeff_value_gas_hour_17=0,coeff_value_gas_hour_18=0,coeff_value_gas_hour_19=0,coeff_value_gas_hour_20=0,coeff_value_gas_hour_21=0,coeff_value_gas_hour_22=0,coeff_value_gas_hour_23=0,
                         coeff_value_gas2_hour_1=0,coeff_value_gas2_hour_2=0,coeff_value_gas2_hour_3=0,coeff_value_gas2_hour_4=0,coeff_value_gas2_hour_5=0,coeff_value_gas2_hour_6=0,coeff_value_gas2_hour_7=0,coeff_value_gas2_hour_8=0,coeff_value_gas2_hour_9=0,coeff_value_gas2_hour_10=0,coeff_value_gas2_hour_11=0,coeff_value_gas2_hour_12=0,coeff_value_gas2_hour_13=0,
                         coeff_value_gas2_hour_14=0,coeff_value_gas2_hour_15=0,coeff_value_gas2_hour_16=0,coeff_value_gas2_hour_17=0,coeff_value_gas2_hour_18=0,coeff_value_gas2_hour_19=0,coeff_value_gas2_hour_20=0,coeff_value_gas2_hour_21=0,coeff_value_gas2_hour_22=0,coeff_value_gas2_hour_23=0,
                         coeff_weekend_hour_1=0,coeff_weekend_hour_2=0,coeff_weekend_hour_3=0,coeff_weekend_hour_4=0,coeff_weekend_hour_5=0,coeff_weekend_hour_6=0,coeff_weekend_hour_7=0,coeff_weekend_hour_8=0,coeff_weekend_hour_9=0,coeff_weekend_hour_10=0,coeff_weekend_hour_11=0,coeff_weekend_hour_12=0,coeff_weekend_hour_13=0,
                         coeff_weekend_hour_14=0,coeff_weekend_hour_15=0,coeff_weekend_hour_16=0,coeff_weekend_hour_17=0,coeff_weekend_hour_18=0,coeff_weekend_hour_19=0,coeff_weekend_hour_20=0,coeff_weekend_hour_21=0,coeff_weekend_hour_22=0,coeff_weekend_hour_23=0,
                         coeff_break_h_hour_1=0,coeff_break_h_hour_2=0,coeff_break_h_hour_3=0,coeff_break_h_hour_4=0,coeff_break_h_hour_5=0,coeff_break_h_hour_6=0,coeff_break_h_hour_7=0,coeff_break_h_hour_8=0,coeff_break_h_hour_9=0,coeff_break_h_hour_10=0,coeff_break_h_hour_11=0,coeff_break_h_hour_12=0,coeff_break_h_hour_13=0,
                         coeff_break_h_hour_14=0,coeff_break_h_hour_15=0,coeff_break_h_hour_16=0,coeff_break_h_hour_17=0,coeff_break_h_hour_18=0,coeff_break_h_hour_19=0,coeff_break_h_hour_20=0,coeff_break_h_hour_21=0,coeff_break_h_hour_22=0,coeff_break_h_hour_23=0),
              data = DTW,
              control=  nls.control(maxiter = 50, tol = 1e-05, minFactor = 1/2100,
                                    printEval = FALSE, warnOnly = FALSE, scaleOffset = 0,
                                    nDcentral = FALSE))

  return(model_h)

}
